// =============================================================================
// top_level.sv : T20 Compute Node Golden Top Level with Inter-FPGA Bridge
// =============================================================================
// Interfaces to T120 Master via:
//   - T20_CLK9    : Bus clock generated by T120 (1.25 .. 10 MHz)
//   - H-bus (Hadamard synchronous stream):
//       TX11_T20_P1 (H_SYNC), TX11_T20_N1 (H_DATA) -> T20 input
//       RX00_T20_P1 (H_ACK),  RX00_T20_N1 (H_STATUS) -> T20 output
//   - S-bus (Service request/response):
//       TX12_T20_P1/N1 (S_TX[0:1]) -> T20 input (2 bits/clk9)
//       RX02_T20_P1/N1, RX03_T20_P1/N1 (S_RX[0:3]) -> T20 output (4 bits/clk9)
//   - Status LEDs:
//       T20_LED1..8 show clock division and bus activity.
// =============================================================================
`timescale 1ns / 1ps
`default_nettype none

module top_level (
    // Clock
    (* syn_peri_port = 0 *) input  wire  CLK_50MHZ,

    // Inter-FPGA Bus Pins (Directions from T20 POV)
    (* syn_peri_port = 0 *) input  wire  T20_CLK9,
    (* syn_peri_port = 0 *) input  wire  TX11_T20_P1,   // H_SYNC
    (* syn_peri_port = 0 *) input  wire  TX11_T20_N1,   // H_DATA
    (* syn_peri_port = 0 *) input  wire  TX12_T20_P1,   // S_TX[0]
    (* syn_peri_port = 0 *) input  wire  TX12_T20_N1,   // S_TX[1]

    (* syn_peri_port = 0 *) output logic RX00_T20_P1,   // H_ACK
    (* syn_peri_port = 0 *) output logic RX00_T20_N1,   // H_STATUS
    (* syn_peri_port = 0 *) output logic RX02_T20_P1,   // S_RX[0]
    (* syn_peri_port = 0 *) output logic RX02_T20_N1,   // S_RX[1]
    (* syn_peri_port = 0 *) output logic RX03_T20_P1,   // S_RX[2]
    (* syn_peri_port = 0 *) output logic RX03_T20_N1,   // S_RX[3]

    // Unused inter-FPGA RX lanes on T20 (inputs tied off / unused)
    (* syn_peri_port = 0 *) input  wire  RX01_T20_N1,
    (* syn_peri_port = 0 *) input  wire  RX01_T20_P1,
    (* syn_peri_port = 0 *) input  wire  RX04_T20_N1,
    (* syn_peri_port = 0 *) input  wire  RX04_T20_P1,
    (* syn_peri_port = 0 *) input  wire  RX05_T20_N1,
    (* syn_peri_port = 0 *) input  wire  RX05_T20_P1,
    (* syn_peri_port = 0 *) input  wire  RX06_T20_N1,
    (* syn_peri_port = 0 *) input  wire  RX06_T20_P1,
    (* syn_peri_port = 0 *) input  wire  RX07_T20_N1,
    (* syn_peri_port = 0 *) input  wire  RX07_T20_P1,

    // Unused inter-FPGA TX lanes on T20 (outputs tied low)
    (* syn_peri_port = 0 *) output logic TX02_T20_N1,
    (* syn_peri_port = 0 *) output logic TX02_T20_P1,
    (* syn_peri_port = 0 *) output logic TX03_T20_N1,
    (* syn_peri_port = 0 *) output logic TX03_T20_P1,
    (* syn_peri_port = 0 *) output logic TX04_T20_N1,
    (* syn_peri_port = 0 *) output logic TX04_T20_P1,
    (* syn_peri_port = 0 *) output logic TX05_T20_N1,
    (* syn_peri_port = 0 *) output logic TX05_T20_P1,
    (* syn_peri_port = 0 *) output logic TX06_T20_N1,
    (* syn_peri_port = 0 *) output logic TX06_T20_P1,
    (* syn_peri_port = 0 *) output logic TX07_T20_N1,
    (* syn_peri_port = 0 *) output logic TX07_T20_P1,
    (* syn_peri_port = 0 *) output logic T20_CLK8,

    // Status LEDs
    (* syn_peri_port = 0 *) output logic T20_LED1,
    (* syn_peri_port = 0 *) output logic T20_LED2,
    (* syn_peri_port = 0 *) output logic T20_LED3,
    (* syn_peri_port = 0 *) output logic T20_LED4,
    (* syn_peri_port = 0 *) output logic T20_LED5,
    (* syn_peri_port = 0 *) output logic T20_LED6,
    (* syn_peri_port = 0 *) output logic T20_LED7,
    (* syn_peri_port = 0 *) output logic T20_LED8,

    // Analog Control & Monitor Outputs
    (* syn_peri_port = 0 *) output logic COMP_LED_ON,
    (* syn_peri_port = 0 *) output logic MAT33_LED_ON,
    (* syn_peri_port = 0 *) output logic HEAT_1_EN,
    (* syn_peri_port = 0 *) output logic HEAT_2_EN,
    (* syn_peri_port = 0 *) output logic HEAT_3_EN,
    (* syn_peri_port = 0 *) output logic HEAT_4_EN,

    // Matrix M3 Hadamard Differential Pairs
    (* syn_peri_port = 0 *) output logic H_M3_N1,
    (* syn_peri_port = 0 *) output logic H_M3_N2,
    (* syn_peri_port = 0 *) output logic H_M3_N3,
    (* syn_peri_port = 0 *) output logic H_M3_N4,
    (* syn_peri_port = 0 *) output logic H_M3_N5,
    (* syn_peri_port = 0 *) output logic H_M3_N6,
    (* syn_peri_port = 0 *) output logic H_M3_N7,
    (* syn_peri_port = 0 *) output logic H_M3_N8,
    (* syn_peri_port = 0 *) output logic H_M3_P1,
    (* syn_peri_port = 0 *) output logic H_M3_P2,
    (* syn_peri_port = 0 *) output logic H_M3_P3,
    (* syn_peri_port = 0 *) output logic H_M3_P4,
    (* syn_peri_port = 0 *) output logic H_M3_P5,
    (* syn_peri_port = 0 *) output logic H_M3_P6,
    (* syn_peri_port = 0 *) output logic H_M3_P7,
    (* syn_peri_port = 0 *) output logic H_M3_P8,

    // Matrix M8 Hadamard Differential Pairs
    (* syn_peri_port = 0 *) output logic H_M8_N1,
    (* syn_peri_port = 0 *) output logic H_M8_N2,
    (* syn_peri_port = 0 *) output logic H_M8_N3,
    (* syn_peri_port = 0 *) output logic H_M8_N4,
    (* syn_peri_port = 0 *) output logic H_M8_N5,
    (* syn_peri_port = 0 *) output logic H_M8_N6,
    (* syn_peri_port = 0 *) output logic H_M8_N7,
    (* syn_peri_port = 0 *) output logic H_M8_P1,
    (* syn_peri_port = 0 *) output logic H_M8_P2,
    (* syn_peri_port = 0 *) output logic H_M8_P3,
    (* syn_peri_port = 0 *) output logic H_M8_P4,
    (* syn_peri_port = 0 *) output logic H_M8_P5,
    (* syn_peri_port = 0 *) output logic H_M8_P6,
    (* syn_peri_port = 0 *) output logic H_M8_P7,

    // Internal Reconfiguration (CONFIG_CTRL0)
    (* syn_peri_port = 0 *) input  wire        cfg_ERROR,
    (* syn_peri_port = 0 *) output logic [1:0] cfg_CBSEL,
    (* syn_peri_port = 0 *) output logic       cfg_CONFIG,
    (* syn_peri_port = 0 *) output logic       cfg_ENA
);

    // =========================================================================
    // Reset generation (power-on reset sequencer)
    // =========================================================================
    logic [7:0] rst_cnt = 8'h00;
    logic       rstn = 1'b0;

    always_ff @(posedge CLK_50MHZ) begin
        if (rst_cnt != 8'hFF) begin
            rst_cnt <= rst_cnt + 8'h01;
            rstn    <= 1'b0;
        end else begin
            rstn    <= 1'b1;
        end
    end

    // Synchronize rstn into T20_CLK9 domain
    logic rstn_clk9_r1, rstn_clk9;
    always_ff @(posedge T20_CLK9 or negedge rstn) begin
        if (!rstn) begin
            rstn_clk9_r1 <= 1'b0;
            rstn_clk9    <= 1'b0;
        end else begin
            rstn_clk9_r1 <= 1'b1;
            rstn_clk9    <= rstn_clk9_r1;
        end
    end

    // =========================================================================
    // H-bus Receiver (Hadamard 16-bit word engine)
    // =========================================================================
    logic [15:0] pad_p, pad_n;
    logic        h_ack;
    logic [15:0] h_word_cnt;
    logic [15:0] h_sync_err;

    logic [15:0] en_mask;
    logic        static_on;
    logic [15:0] static_vec;

    t20_hbus_rx #(.W(16)) u_hbus_rx (
        .clk9         (T20_CLK9),
        .rstn         (rstn_clk9),
        .h_sync       (TX11_T20_P1),
        .h_data       (TX11_T20_N1),
        .en_mask      (en_mask),
        .static_on    (static_on),
        .static_vec   (static_vec),
        .pad_p        (pad_p),
        .pad_n        (pad_n),
        .ack          (h_ack),
        .word_cnt     (h_word_cnt),
        .sync_err_cnt (h_sync_err)
    );

    assign RX00_T20_P1 = h_ack;
    assign RX00_T20_N1 = 1'b0;  // spare H_STATUS

    // Drive matrix M3 pads
    assign H_M3_P1 = pad_p[0];
    assign H_M3_N1 = pad_n[0];
    assign H_M3_P2 = pad_p[1];
    assign H_M3_N2 = pad_n[1];
    assign H_M3_P3 = pad_p[2];
    assign H_M3_N3 = pad_n[2];
    assign H_M3_P4 = pad_p[3];
    assign H_M3_N4 = pad_n[3];
    assign H_M3_P5 = pad_p[4];
    assign H_M3_N5 = pad_n[4];
    assign H_M3_P6 = pad_p[5];
    assign H_M3_N6 = pad_n[5];
    assign H_M3_P7 = pad_p[6];
    assign H_M3_N7 = pad_n[6];
    assign H_M3_P8 = pad_p[7];
    assign H_M3_N8 = pad_n[7];

    // Drive matrix M8 pads (7 rows)
    assign H_M8_P1 = pad_p[8];
    assign H_M8_N1 = pad_n[8];
    assign H_M8_P2 = pad_p[9];
    assign H_M8_N2 = pad_n[9];
    assign H_M8_P3 = pad_p[10];
    assign H_M8_N3 = pad_n[10];
    assign H_M8_P4 = pad_p[11];
    assign H_M8_N4 = pad_n[11];
    assign H_M8_P5 = pad_p[12];
    assign H_M8_N5 = pad_n[12];
    assign H_M8_P6 = pad_p[13];
    assign H_M8_N6 = pad_n[13];
    assign H_M8_P7 = pad_p[14];
    assign H_M8_N7 = pad_n[14];

    // =========================================================================
    // S-bus Receiver (T120 -> T20, 2 bits per clk9)
    // =========================================================================
    logic        s_rx_frame_ok;
    logic        s_rx_frame_err;
    logic        s_rx_frame_ovf;
    logic [7:0]  s_rx_ch;
    logic [7:0]  s_rx_seqop;
    logic [10:0] s_rx_len;
    logic [63:0] s_rx_pay8;

    t20_sbus_rx u_sbus_rx (
        .clk9       (T20_CLK9),
        .rstn       (rstn_clk9),
        .sym        ({TX12_T20_N1, TX12_T20_P1}), // 2-bit symbol
        .buf_busy   (1'b0),
        .ram_we     (),
        .ram_waddr  (),
        .ram_wdata  (),
        .rx_ch      (s_rx_ch),
        .rx_seqop   (s_rx_seqop),
        .rx_len     (s_rx_len),
        .pay8       (s_rx_pay8),
        .frame_ok   (s_rx_frame_ok),
        .frame_err  (s_rx_frame_err),
        .frame_ovf  (s_rx_frame_ovf)
    );

    // =========================================================================
    // S-bus Hardware Responder (Golden Image responder, 0x06 ACK / 0x15 NAK)
    // =========================================================================
    logic        s_tx_start;
    logic [7:0]  s_tx_resp;
    logic [7:0]  s_tx_ch;
    logic [7:0]  s_tx_seqop;
    logic [10:0] s_tx_len;
    logic [9:0]  s_tx_pay_idx;
    logic [7:0]  s_tx_pay_byte;
    logic        s_tx_busy;
    logic [15:0] s_good_cnt;
    logic [15:0] s_crc_err_cnt;
    logic        s_nak_sticky;

    t20_hw_responder #(.HAS_SOC(0)) u_hw_responder (
        .clk9        (T20_CLK9),
        .rstn        (rstn_clk9),
        .frame_ok    (s_rx_frame_ok),
        .frame_err   (s_rx_frame_err),
        .rx_ch       (s_rx_ch),
        .rx_seqop    (s_rx_seqop),
        .pay8        (s_rx_pay8),
        .h_word_cnt  (h_word_cnt),
        .h_sync_err  (h_sync_err),
        .tx_busy     (s_tx_busy),
        .tx_start    (s_tx_start),
        .tx_resp     (s_tx_resp),
        .tx_ch       (s_tx_ch),
        .tx_seqop    (s_tx_seqop),
        .tx_len      (s_tx_len),
        .tx_pay_idx  (s_tx_pay_idx),
        .tx_pay_byte (s_tx_pay_byte),
        .fwd_to_soc  (),
        .en_mask     (en_mask),
        .static_on   (static_on),
        .static_vec  (static_vec),
        .good_cnt    (s_good_cnt),
        .crc_err_cnt (s_crc_err_cnt),
        .nak_sticky  (s_nak_sticky),
        .cfg_cbsel   (resp_cfg_cbsel),
        .cfg_config  (resp_cfg_config),
        .cfg_ena     (resp_cfg_ena)
    );

    // =========================================================================
    // CONFIG_CTRL0 Reconfiguration Controller (Driven by CLK_50MHZ)
    // =========================================================================
    logic [1:0] resp_cfg_cbsel;
    logic       resp_cfg_config;
    logic       resp_cfg_ena;

    // Cross reconfig trigger from T20_CLK9 into CLK_50MHZ domain
    logic resp_cfg_config_r1, resp_cfg_config_r2;
    logic [7:0] reconfig_timer = 8'd0;
    logic       reconfig_active = 1'b0;

    always_ff @(posedge CLK_50MHZ or negedge rstn) begin
        if (!rstn) begin
            resp_cfg_config_r1 <= 1'b0;
            resp_cfg_config_r2 <= 1'b0;
            cfg_CBSEL          <= 2'b00;
            cfg_ENA            <= 1'b0;
            cfg_CONFIG         <= 1'b0;
            reconfig_timer     <= 8'd0;
            reconfig_active    <= 1'b0;
        end else begin
            resp_cfg_config_r1 <= resp_cfg_config;
            resp_cfg_config_r2 <= resp_cfg_config_r1;

            if (resp_cfg_config_r2 && !reconfig_active) begin
                reconfig_active <= 1'b1;
                reconfig_timer  <= 8'd0;
                cfg_CBSEL       <= resp_cfg_cbsel;
                cfg_ENA         <= 1'b1;
                cfg_CONFIG      <= 1'b0;
            end else if (reconfig_active) begin
                reconfig_timer <= reconfig_timer + 8'd1;
                // Efinix CONFIG_CTRL0 protocol:
                // Present CBSEL & ENA first, then assert CONFIG high after a few cycles
                if (reconfig_timer >= 8'd16 && reconfig_timer < 8'd240) begin
                    cfg_CONFIG <= 1'b1;
                end else if (reconfig_timer >= 8'd240) begin
                    cfg_CONFIG      <= 1'b0;
                    cfg_ENA         <= 1'b0;
                    reconfig_active <= 1'b0;
                end
            end
        end
    end

    // =========================================================================
    // S-bus Transmitter (T20 -> T120, 4 bits per clk9)
    // =========================================================================
    logic [3:0] s_tx_nib;

    t20_sbus_tx u_sbus_tx (
        .clk9     (T20_CLK9),
        .rstn     (rstn_clk9),
        .start    (s_tx_start),
        .resp     (s_tx_resp),
        .ch       (s_tx_ch),
        .seqop    (s_tx_seqop),
        .len      (s_tx_len),
        .pay_idx  (s_tx_pay_idx),
        .pay_byte (s_tx_pay_byte),
        .busy     (s_tx_busy),
        .done     (),
        .nib      (s_tx_nib)
    );

    assign RX02_T20_P1 = s_tx_nib[0];
    assign RX02_T20_N1 = s_tx_nib[1];
    assign RX03_T20_P1 = s_tx_nib[2];
    assign RX03_T20_N1 = s_tx_nib[3];

    // =========================================================================
    // Heartbeat & Status LEDs
    // =========================================================================
    logic [25:0] hb_cnt = 26'd0;
    always_ff @(posedge CLK_50MHZ) begin
        hb_cnt <= hb_cnt + 26'd1;
    end

    // LED assignments for Custom Application:
    // LED8: Blink/heartbeat from 50 MHz oscillator (~1.5 Hz)
    // LED7: Traffic/activity from T20_CLK9 bus clock
    // LED6: Active traffic on H-bus (TX11_T20_P1 sync / h_ack)
    assign T20_LED8 = hb_cnt[24];              // Heartbeat from 50 MHz clock
    assign T20_LED7 = T20_CLK9;                // Traffic / bus clock indicator from T20_CLK9
    assign T20_LED6 = TX11_T20_P1 | h_ack;     // H-bus active traffic indicator
    assign T20_LED5 = s_rx_frame_ok;           // S-bus RX frame received
    assign T20_LED4 = s_tx_busy;               // S-bus TX active
    assign T20_LED3 = |h_word_cnt;             // H words applied
    assign T20_LED2 = 1'b0;                    // Off (distinguishes Custom from Golden Image)
    assign T20_LED1 = 1'b0;                    // Off / spare

    // Peripheral tie-offs
    assign COMP_LED_ON  = 1'b0;
    assign MAT33_LED_ON = 1'b0;
    assign HEAT_1_EN    = 1'b0;
    assign HEAT_2_EN    = 1'b0;
    assign HEAT_3_EN    = 1'b0;
    assign HEAT_4_EN    = 1'b0;

    assign TX02_T20_N1  = 1'b0;
    assign TX02_T20_P1  = 1'b0;
    assign TX03_T20_N1  = 1'b0;
    assign TX03_T20_P1  = 1'b0;
    assign TX04_T20_N1  = 1'b0;
    assign TX04_T20_P1  = 1'b0;
    assign TX05_T20_N1  = 1'b0;
    assign TX05_T20_P1  = 1'b0;
    assign TX06_T20_N1  = 1'b0;
    assign TX06_T20_P1  = 1'b0;
    assign TX07_T20_N1  = 1'b0;
    assign TX07_T20_P1  = 1'b0;
    assign T20_CLK8     = 1'b0;

endmodule
`default_nettype wire
